---
title: "Plotting MRIQC Stats"
output: html_document
author: Gabrielle Herman
always_allow_html: yes
---


```{r}
library(tidyverse)
library(grid)
library(gridExtra)
```



```{r, some plotting functions}
plot_mriqc_metric <- function(mriqc,metric,title){
  
 plot <- ggplot(data=mriqc, mapping = aes_string(x="subj", y=metric)) + geom_boxplot(outlier.shape=NA, width=0.75, colour="gray82") + geom_jitter(width=0.3, aes( fill=site, shape=site), size=3)+theme_classic(base_size=10)+theme(panel.background = element_rect(fill="white", colour="white"),axis.title.x=element_blank(),axis.title.y = element_text())+labs(y=title) +scale_shape_manual(values=shapez)+scale_fill_manual(values=fillz) +guides(fill=guide_legend("scanner"), shape=guide_legend("scanner"))
  
  return(plot)

}


grid_arrange_shared_legend <- function(...) {
    plots <- list(...)
    g <- ggplotGrob(plots[[1]] + theme(legend.position="bottom"))$grobs
    legend <- g[[which(sapply(g, function(x) x$name) == "guide-box")]]
    lheight <- sum(legend$height)
    
  grid.arrange(arrangeGrob(grobs=lapply(plots, function(x)
      x + theme(legend.position="none",aspect.ratio=0.6))),
    legend,
    ncol = 1,
    heights = unit.c(unit(1, "npc") - lheight, lheight),
    widths = unit(0.5, "npc")
    
    )

}

```



```{r, reading in func mriqc}
func<- read.csv('../data/group_bold.tsv', sep='\t') %>%
  mutate(subj = substr(bids_name,1, 6), year = substr(bids_name, 8, 13), site=substr(bids_name, 14, 16), parent_site=substr(bids_name,14,15)) %>% mutate(scanner_type= ifelse(substr(bids_name,16,16)=="P", "prisma","GE")) %>% filter(subj!="sub-05")
#sub-05 is purposefully removed from the data, only has one partial acquisition
```

```{r, write csv summarizing func output}
func_output <- func %>% select(bids_name, scanner=site, parent_site, scanner_type, subj, year,  tsnr, snr, dvars_nstd, fd_mean, fd_perc)

write.csv(func_output, "../out/func_summary.csv")
```



```{r, testing more plotting, eval=FALSE, include=FALSE}
mriqc=func
metric="tsnr"


fillz=c(NA, "black",NA,"black",NA,"black")

names(fillz)= c("CMH", "CMP", "MRC" ,"MRP", "ZHH" ,"ZHP")


ggplot(data=mriqc, mapping = aes_string(x="subj", y=metric)) + geom_boxplot(outlier.shape=NA, width=0.8)+ geom_jitter(width=0.1, aes( fill=scanner_type, shape=parent_site))+theme_classic(base_size=6)+theme(panel.background = element_rect(fill="white", colour="white"),axis.title.x=element_blank()) +scale_shape_manual(values=c(21,23,24))+scale_fill_manual(values=c(NA,"black")) +guides(fill=guide_legend("title"), shape=guide_legend("title")) 


```



```{r, testing more plotting2, eval=FALSE, include=FALSE}
mriqc=func
metric="tsnr"

shapez=c("\u26AA","\u2605","\u2662","\u26AB","\u2606","\u2666") #cool so this works but not when the types are mixed bw unicode and numbers?
names(shapez)=c("CMH","MRP","ZHH","CMP","MRC","ZHP")



fillz=c(NA,"black",NA,"black",NA,"black")
names(fillz)=c("CMH","MRP","ZHH","CMP","MRC","ZHP")


ggplot(data=mriqc, mapping = aes_string(x="subj", y=metric)) + geom_jitter(width=0.1, size=6, aes( fill=site, shape=site))+theme_classic(base_size=12)+theme(panel.background = element_rect(fill="white", colour="white"),axis.title.x=element_blank()) +scale_shape_manual(values=shapez)+scale_fill_manual(values=fillz) +guides(fill=guide_legend("title"), shape=guide_legend("title"))


```



```{r, set shapes and fills for plots}

shapez=c("\u26AA","\u2605","\u2662","\u26AB","\u2606","\u2666")
names(shapez)=c("CMH","MRP","ZHH","CMP","MRC","ZHP")



fillz=c(NA,"black",NA,"black",NA,"black")
names(fillz)=c("CMH","MRP","ZHH","CMP","MRC","ZHP")

```

```{r, plot fmri metrics of interest}

tsnr <- plot_mriqc_metric(func,"tsnr","tSNR")

dvars <- plot_mriqc_metric(func, "dvars_nstd","DVARS")

fd_mean <- plot_mriqc_metric(func,"fd_mean","Mean FD (mm)")


plt <- grid_arrange_shared_legend(dvars, tsnr, fd_mean)

ggsave(file="../out/fmri_plots.tiff",plt, width =7, height=5)


```



```{r, read in T1 data}
T1 <- read.csv('../data/group_T1w.tsv', sep='\t') %>%
  mutate(subj = substr(bids_name,1, 6), year = substr(bids_name, 8, 13), site=substr(bids_name, 14, 16), parent_site=substr(bids_name,14,15))%>% mutate(scanner_type= ifelse(substr(bids_name,16,16)=="P", "prisma","GE")) %>% filter(subj!="sub-05")
```


```{r, write csv summarizing T1 output}
t1_output <- T1 %>% select(bids_name, scanner=site, parent_site, scanner_type, subj, year,  cnr, snr_csf,	snr_gm,	snr_total,	snr_wm,	snrd_csf,	snrd_gm,	snrd_total,	snrd_wm)

write.csv(t1_output, "../out/T1w_summary_july.csv")

```


```{r,plot T1 metrics of interest}

cnr <- plot_mriqc_metric(T1,"cnr", "CNR") #(there is a placeholder to maintain aspect ratio)

snr_total <- plot_mriqc_metric(T1, "snr_total", "SNR")

snrd_total <- plot_mriqc_metric(T1, "snrd_total", "SNRD(remove)")



plt <- grid_arrange_shared_legend(snrd_total,snr_total, cnr)

ggsave(file="../out/t1_plots.tiff",plt, width =7, height=5)

plt
```
