---
title: "Plotting DTI QA stats"
author: Gabrielle Herman
output: html_document
---

```{r}
library(tidyverse)
library(grid)
library(gridExtra)
```

```{r, read in data}
dti <- read.csv("../data/eddy_metrics.csv") %>% mutate(year=substr(session_label, 0, 6), site=substr(session_label, 7, 9), record_id=subject_id, parent_site=substr(session_label, 7, 8))%>% mutate(scanner_type= ifelse(substr(site,3,3)=="P", "prisma","GE")) %>% mutate(subj=subject_id)
```


```{r, some plotting functions}

shapez=c("\u26AA","\u2605","\u2662","\u26AB","\u2606","\u2666") #cool so this works but not when the types are mixed
names(shapez)=c("CMH","MRP","ZHH","CMP","MRC","ZHP")
fillz=c(NA,"black",NA,"black",NA,"black")
names(fillz)=c("CMH","MRP","ZHH","CMP","MRC","ZHP")


plot_mriqc_metric <- function(mriqc,metric,title){
  
 plot <- ggplot(data=mriqc, mapping = aes_string(x="subj", y=metric)) + geom_boxplot(outlier.shape=NA, width=0.75, colour="gray82") + geom_jitter(width=0.3, aes( fill=site, shape=site), size=2)+theme_classic(base_size=10)+theme(panel.background = element_rect(fill="white", colour="white"),axis.title.x=element_blank(),axis.title.y = element_text())+labs(y=title) +scale_shape_manual(values=shapez)+scale_fill_manual(values=fillz) +guides(fill=guide_legend("title"), shape=guide_legend("title"))
  
  return(plot)

}


grid_arrange_shared_legend <- function(...) {
    plots <- list(...)
    g <- ggplotGrob(plots[[1]] + theme(legend.position="bottom"))$grobs
    legend <- g[[which(sapply(g, function(x) x$name) == "guide-box")]]
    lheight <- sum(legend$height)
    
  grid.arrange(arrangeGrob(grobs=lapply(plots, function(x)
      x + theme(legend.position="none",aspect.ratio=0.6))),
    legend,
    ncol = 1,
    heights = unit.c(unit(1, "npc") - lheight, lheight),
    widths = unit(0.5, "npc")
    
    )

}
```


```{r, testing plotting, eval=FALSE, include=FALSE}
plot_mriqc_metric(dti, "avg_snr_0")
```

```{r, plotting some metrics}


fd_mean <- plot_mriqc_metric(dti,"qc_mot_rel","Mean FD (mm)")

snr <- plot_mriqc_metric(dti, "avg_snr_0","SNR")

cnr <- plot_mriqc_metric(dti,"avg_cnr_1000","CNR")

plt <- grid_arrange_shared_legend(snr, cnr, fd_mean)

ggsave(file="../out/dwi_plots.tiff",plt, width =7, height=5) #might have to fix it in illustrator after or something...

```

